---
- name: Install local Requirements
  hosts: localhost
  connection: local
  roles:
    - requirements

- name: Install Ledger Database
  hosts: database
  roles:
    - database
    
- name: Install Ledger Web Servers
  hosts: web
  vars:
    parser: false
  roles:
    - web
    
- name: Install Ledger Parser Servers
  hosts: parser
  vars:
    parser: true
  roles:
    - web
