- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart php
  ansible.builtin.service:
    name: php-fpm
    state: restarted

- name: Restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
